import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../app/(component)/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Next Authentication",
  description: "Generated by Ahmad Bilal",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Navbar />
          <section className="min-h-screen bg-red-500 text-white">
            {children}
          </section>
        </body>
      </html>
    </ClerkProvider>
  );
}
